config/routes.rb
Rails.application.routes.draw do
  get 'webstudios/index'

  get 'webstudios/filter'

  get 'webstudios/show'

  get 'webstudios/:id/edit/' => 'webstudios#edit'

  patch 'webstudios/:id' => 'webstudios#update'

  get 'webstudios/:id' => 'webstudios#show', as: :webstudio

  devise_for :users
  root "webstudios#index"

end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :webstudios
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	belongs_to :webstudio
	accepts_nested_attributes_for :webstudio
end

app/models/webstudio.rb
class Webstudio < ActiveRecord::Base
	belongs_to :city
	has_one :user
	mount_uploader :img, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:email, :password, :password_confirmation, webstudio_attributes: [:name, :description, :img, :city_id]]
    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end

end

app/controllers/webstudios_controller.rb
class WebstudiosController < ApplicationController
  def index
    @c = City.all
  	@ws=Webstudio.all
  end

  def filter
    @c = City.all
    @ws = Webstudio.all
    @ws = @ws.where(city_id: params[:filter][:city_id]) unless params[:filter][:city_id].empty?
    @ws = @ws.where("average_ticket < ?", params[:filter][:pricehigh]) unless params[:filter][:pricehigh].empty? 
    @ws = @ws.where("average_ticket > ?", params[:filter][:pricelow]) unless params[:filter][:pricelow].empty?
  end

  def show
  	@wd=Webstudio.find(params[:id]) 
  end

  def edit
  	@wd=Webstudio.find(params[:id]) 
    unless @wd.user == current_user
      redirect_to :action => "index"
    end
  end

  def update
  	@wd=Webstudio.find(params[:id])
  	@wd.update_attributes(webstudio_params)
  	redirect_to :action => "show"
  end

  private

  def webstudio_params
  	params.require(:webstudio).permit(:name, :average_ticket, :description, :img)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/webstudios_helper.rb
module WebstudiosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sortfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'FFF', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      	<% if current_user.nil? %>
        <li><%= link_to 'Регистрация', new_user_registration_path%></li>
		<li><%= link_to 'Вход', new_user_session_path%></li>
       	<% else %>
       	
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Аккаунт<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#"><%= link_to 'Настройки аккаунта', edit_user_registration_path %></a></li>
            <li><a href="#"><%= link_to 'Изменить данные моей веб студии', controller: "webstudios", action: "edit", id: current_user.webstudio %></a></li>
            <li class="divider"></li>
            <li><a href="#"><%= link_to 'Выход', destroy_user_session_path, method: :delete %></a></li>
          </ul>
        </li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/webstudios/edit.html.erb
<%= simple_form_for(@wd, html: { class: 'form-horizontal' }, :method => :patch) do |form|%>
  <%= form.input :name, as: :string, label: 'Название'%>
  <%= form.input :average_ticket, as: :string, label: 'Средний чек'%>
  <%= form.input :description, as: :text, label: 'Описание'%>
  <%= form.input :img, as: :file, label: 'Изображение'%>
  <%= form.button :submit, 'Изменить'%>
<%end%>

app/views/webstudios/filter.html.erb
<%= simple_form_for :filter, :url =>  webstudios_filter_path, :method => :get do |f| %>
  <%= f.input :pricelow, as: :string, label: 'Минимальная цена'%>
  <%= f.input :pricehigh, as: :string, label: 'Максимальная цена'%>
  <%= f.input :city_id, collection: @c.map %>
  <%= f.button :submit, 'Поиск'%>
<%end%>

<br>


<div class="row">
<div class="row">
  <%@ws.each do |ws|%>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%=image_tag(ws.img)%>
      <div class="caption">
        <h3><%=ws.name%></h3>
        <p><%=ws.description%></p>
        <p>Средний чек: <%=ws.average_ticket%></p>
        <p>Город: <%=ws.city.name%></p>
        <p>
    <%= link_to 'Посмотреть', webstudio_path(ws), {class: "btn btn-primary", role: "button"} %>
           </p> 
      </div>
    </div>
    </div>
  <%end%>
</div>
</div>

app/views/webstudios/index.html.erb
<%= simple_form_for :filter, :url =>  webstudios_filter_path, :method => :get do |f| %>
  <%= f.input :pricelow, as: :string, label: 'Минимальная цена'%>
  <%= f.input :pricehigh, as: :string, label: 'Максимальная цена'%>
  <%= f.input :city, collection: @c.map %>
  <%= f.button :submit, 'Поиск'%>
<%end%>

<br>
<div class="row">
	<%@ws.each do |ws|%>
	<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%=image_tag(ws.img)%>
      <div class="caption">
        <h3><%=ws.name%></h3>
        <p><%=ws.description%></p>
        <p>Средний чек: <%=ws.average_ticket%></p>
        <p>Город: <%=ws.city.name%></p>
        <p>
		<%= link_to 'Посмотреть', webstudio_path(ws), {class: "btn btn-primary", role: "button"} %>
        	 </p> 
      </div>
    </div>
    </div>
	<%end%>
</div>

app/views/webstudios/show.html.erb
<h3><%=@wd.name%></h3>
<%=image_tag(@wd.img)%>
<h4><%=@wd.description%></h4>
<p>Город: <%=@wd.city.name%></p>